# Generated by Django 5.1.2 on 2025-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the inventory item', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the item', null=True)),
                ('quantity', models.IntegerField(default=0, help_text='Current quantity in stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the item was last updated')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['name'],
            },
        ),
    ]
